### PR TITLE
Fix build problems

### PR DESCRIPTION
**Pull request by mate-from-mattr**
Fixes clippy warnings and a problem that blocked Android build.

## Description

Clippy warnings were causing the master branch to fail. All pull requests from Dependabot also fail. I used `cargo clippy --fix` and fixed other warnings manually. 

The build_android job was also failing. Seemed to be because the NDK inside the Github Action is using a new version. The job now uses [https://github.com/nttld/setup-ndk](setup-ndk) action to install [r21e](https://github.com/nttld/setup-ndk). The Rust Android tool chain is compatible with version 21 (and 21 was already specified in the build.sh script).

- [x] ~Tests for the changes have been added (for bug fixes / features)~
- [x] The commit message(s) follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Documentation has been added / updated (for bug fixes / features)
- [x] Changes follow the **[contributing](../docs/contributing.md)** document.

## Motivation and Context

All our GitHub checks need to pass and this will fix them.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Which merge strategy will you use?

- [ ] Squash
- [x] Rebase (REVIEW COMMITS)

### CODE REVIEW

**Review by tplooker — APPROVED** [review]

**Review by tplooker — CHANGES_REQUESTED** [review]
Looks like its still failing @mate-from-mattr

**Comment by mate-from-mattr** [comment]
@tplooker Looks like _Build & Test_ needed the same treatment as _build\_android_. All checks have passed now!

**Review by BenLiuMattr — COMMENTED** [review]
Nice work!

**Review by tplooker — APPROVED** [review]

**Comment by mate-from-mattr** [comment]
Thanks for merging @tplooker

**Pull request merged**
