### PR TITLE
feat: make return values of verify blind commitment functions consistent

### PR DESCRIPTION
**Pull request by aliXsed**
## Description
Verify blind commit functions should return a result which is either 0(success) or 1(fail) consistent with all the other similar apis in this library. They should also set the error uniformly at all the stages and for all possible faults. This change makes the enum SignatureProofStatus redundant and thus it is removed.

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] The commit message(s) follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] Changes follow the **[contributing](../docs/contributing.md)** document.

## Motivation and Context
Improving both consistency and error reporting. Removing an unnecessary enum type.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No
It's a breaking change due to the fact that the return value of an api is changed. However, these functions are not used widely and that's the reason why their interface design had been left behind the other APIs.

## Which merge strategy will you use?

- [x] Squash
- [ ] Rebase (REVIEW COMMITS)

### CODE REVIEW

**Comment by tmarkovski** [comment]
Tagging myself to make updates to the dotnet wrapper, since there are breaking changes. We use these library in production, so I would be careful concluding how widely these are used.
This change would (should, if we generate them on the fly) effectively break the unit tests.

**Review by tplooker — APPROVED** [review]
LGTM thanks!

**Comment by tplooker** [comment]
@tmarkovski are you happy with us going ahead with this PR?

**Comment by tmarkovski** [comment]
Yes, I'm sorry, I should've made it clear that I wasn't looking to hold the PR, just make a personal note for myself.

**Pull request merged**
