### PR TITLE
fix: update dev deps to remove alerts

### PR DESCRIPTION
**Pull request by mate-from-mattr**
Fixes Dependabot alerts by updating some developer dependencies.

## Description

See the references section for wider context on why we need these updates.

1. Updates commit linting packages to remove `semver` vulnerability.
2. Uses latest 6.x version of `pytest` to remove `py` vulnerability.
3. Rust clippy also complained about minor code problems. I pushed changes to get the GitHub action to pass again.
4. Update the Android Native Development Kit (NDK) to v23. This is the latest version compatible with Rust.
5. Python 3.6 - 3.9 are at end-of-life and `actions/setup-python` no longer supports them on the latest Ubuntu. So we've dropped them.

- [ ] ~Tests for the changes have been added (for bug fixes / features)~
- [x] The commit message(s) follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Documentation has been added / updated (for bug fixes / features)
- [x] Changes follow the **[contributing](../docs/contributing.md)** document.

## Motivation and Context

Part of MATTR's initiative to remove security vulnerabilities.

image

## References

1. [Rust Blog - Android NDK update](https://blog.rust-lang.org/2023/01/09/android-ndk-update-r25.html).
2. [actions/setup-python issue - why Python 3.6 no longer works](https://github.com/actions/setup-python/issues/561#issuecomment-1340657956).
3. [Supported versions of Python](https://devguide.python.org/versions/).
6. [Android NDK Revision History](https://developer.android.com/ndk/downloads/revision_history)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Which merge strategy will you use?

- [x] Squash
- [ ] Rebase (REVIEW COMMITS)

### CODE REVIEW

**Comment by mate-from-mattr** [comment]
https://blog.rust-lang.org/2023/01/09/android-ndk-update-r25.html

**Comment by mate-from-mattr** [comment]
https://github.com/actions/setup-python/issues/561#issuecomment-1340657956

**Comment by mate-from-mattr** [comment]
https://github.com/nardew/talipp/issues/75#issue-1907218243

**Comment by mate-from-mattr** [comment]
https://devguide.python.org/versions/ 
image

**Comment by mate-from-mattr** [comment]
https://stackoverflow.com/a/48154263

**Review by afonsobarracha — APPROVED** [review]

**Pull request merged**
